export const assets = [
    {name:"clamper", url:"./clampy.png"},
    {name:"dragonite", url:"./dragonite.png"},
    {name:"clampersvg", url:"./clampy.svg"},
    {name:"startgame", url:"./sgame.png"},
    {name:"bgimg", url:"./backgroundng.png"},
    {name: "dino", url:"./Idle (1).png"},
    {name: "target", url:"./target.png"},
    {name: "back", url:"./back.png"},
    {name: "pauseDown", url:"./pauseDown.png"},
    {name: "pauseUp", url:"./pauseUp.png"},
    {name: "tempscreen", url:"./temp.png"},
    {name: "sendButton", url:"./send.png"},
    // {name: "dinosheet", url:"./dinosheet.png"},
    // {name: "dinojson", url:"./dinosheet.json"},
];